language: node_js
node_js:
    - "10"
cache:
    directories:
        - node_modules
install:
    - npm install -g codecov
    - npm install @testing-library/jest-dom
notifications:
    email: false
script:
    - npm run build
    - npm run coverage
    - codecov
